# Use Ubuntu as base image
FROM ubuntu

# Update and install required packages
RUN apt-get update && apt-get -y upgrade && \
    apt-get -y install openjdk-8-jdk wget

# Set up Tomcat
ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

# Download and extract Tomcat
RUN mkdir -p $CATALINA_HOME && \
    wget -qO- http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.tar.gz | tar xvz --strip-components=1 -C $CATALINA_HOME

# Copy the application war file into the webapps directory
COPY addressbook.war $CATALINA_HOME/webapps/

# Expose port 8080
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
